kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: aws-efs

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-demo-claim
  namespace: demo
  labels:
    ss: efs-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
